#!/bin/sh
url=${1:-localhost:8080}
content() {
	cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
}
t=`mktemp`
echo "{ \"id\": 1, \"title\": \"`date '+%Y-%m-%d %H:%M:%S'`\", \"content\": \"autogenerated record `content`\" }" > "$t"
ab -n 100 "$url"/todos
ab -n 100 -p "$t" "$url"/todos
ab -n 100 -p "$t" "$url"/todos/1
rm "$t"
